import type { CliProviderId } from './cli-providers.ts';
import { remoteId } from './peers.ts';

/**
 * D65 (`docs/peers.md` → *Taking a session over*): the pure part of taking a
 * session over from one paired machine to another: the wire shapes both
 * machines' take-over routes speak, matching a session's repos to the target's
 * saved folders by remote URL, the clone decision, the rollback plan, the temp
 * branch names and the texts. No file system, no git, no network: `src/server/takeover/`
 * does the work and calls these.
 */

/** The namespace of the temporary remote branches (`switchboard/takeover/<session short id>/<branch>`). */
export const TAKEOVER_BRANCH_PREFIX = 'switchboard/takeover/';

/** Largest conversation file the transfer accepts (200 MB; the cap is checked on both sides). */
export const TAKEOVER_FILE_MAX_BYTES = 200 * 1024 * 1024;

/** Raw bytes per transfer chunk (base64 in JSON stays under the peer API's 1 MiB body limit). */
export const TAKEOVER_CHUNK_BYTES = 512 * 1024;

/** The steps of a take-over, in order (the dialog shows one line per step). */
export const TAKEOVER_STEPS = ['checks', 'stop', 'capture', 'transfer', 'apply', 'resume', 'finish'] as const;

/** One of {@link TAKEOVER_STEPS}. */
export type TakeoverStepId = (typeof TAKEOVER_STEPS)[number];

/** The dialog's label of each step. */
export const TAKEOVER_STEP_LABELS: Readonly<Record<TakeoverStepId, string>> = {
  checks: 'Checking both machines',
  stop: 'Stopping the session where it runs',
  capture: 'Pushing the work in progress to a temporary branch',
  transfer: 'Copying the conversation',
  apply: 'Restoring the working tree here',
  resume: 'Resuming the session',
  finish: 'Closing the old session and cleaning up',
};

/** Where a step stands. */
export type TakeoverStepStatus = 'pending' | 'running' | 'done' | 'failed' | 'skipped';

/** What the dialog's repo row says will happen to one repo on the target. */
export type RepoAction = 'use' | 'clone' | 'blocked';

/** A file of the session's own conversation (a Claude Code transcript, a Codex rollout, an export), as the preview lists it. */
export interface ConversationFileInfo {
  /**
   * Path relative to the conversation's root on that machine (`<id>.jsonl`,
   * `<id>/subagents/agent-1.jsonl`, `rollout/2026/10/04/rollout-….jsonl`); a name
   * starting with `@` is generated by the source (`@chat.md`, `@messages.json`).
   */
  readonly name: string;
  readonly size: number;
}

/** A conversation file with its checksum (the transfer's list). */
export interface ConversationFile extends ConversationFileInfo {
  /** Hex sha256 of the whole file. */
  readonly sha256: string;
}

/** How the conversation travels: its own files, or an exported chat the new agent reads (D62 handover). */
export type ConversationKind = 'claude-transcript' | 'codex-rollout' | 'handover';

/** One git repo a session works in, as the source machine reads it. */
export interface SourceRepo {
  /** Stable within one take-over (the repo's solution / folder name, made unique). */
  readonly key: string;
  /** The solution / repo name. */
  readonly name: string;
  /** `worktree` = the session works in a worktree Switchboard (or its agent) made; `main` = in the repo's own checkout. */
  readonly kind: 'main' | 'worktree';
  /** Where the session works on the source (the worktree, or the checkout). */
  readonly path: string;
  /** The repo's main checkout on the source (equal to `path` for `main`). */
  readonly mainPath: string;
  readonly branch: string;
  readonly remoteName: string;
  /** The remote's URL with any credentials removed. */
  readonly remoteUrl: string;
  /** {@link normalizeRemoteUrl} of it: what repos are matched by. */
  readonly remoteKey: string;
  readonly headSha: string;
  /** The branch's upstream (`origin/feature`), `null` when it has none. */
  readonly upstream: string | null;
  /** Commits not on the upstream; `null` without an upstream. */
  readonly ahead: number | null;
  /** Uncommitted files (untracked ones included, ignored ones not). */
  readonly dirty: { readonly modified: number; readonly untracked: number; readonly total: number };
  /** A worktree's base ref / stacked parent (copied onto the worktree record on the target). */
  readonly baseRef: string | null;
  readonly parentBranch: string | null;
}

/** What the source machine reports about a session it could hand over (`POST /api/takeover/source/inspect`). */
export interface SourceInspect {
  readonly machine: { readonly id: string; readonly name: string };
  readonly platform: string;
  readonly sessionId: string;
  readonly name: string;
  readonly title: string | null;
  readonly task: string;
  readonly provider: CliProviderId;
  readonly claudeSessionId: string;
  /** Codex thread id / OpenCode session id; `null` for Claude Code and when unknown. */
  readonly nativeId: string | null;
  readonly origin: 'switchboard' | 'terminal';
  readonly cwd: string | null;
  /** The session's folder (workspace root or repo). */
  readonly folder: { readonly path: string; readonly kind: 'workspace' | 'repo' | 'plain' } | null;
  readonly solutions: readonly string[];
  readonly worktrees: boolean;
  readonly branch: string | null;
  readonly model: string | null;
  readonly effort: string | null;
  readonly ultracode: boolean;
  readonly hooked: boolean;
  /** The hooked terminal's `claude` process on the source, when known. */
  readonly terminalPid: number | null;
  /** A process of the session runs now (it is paused, then resumed again if the take-over fails). */
  readonly live: boolean;
  /** A turn runs or waits: the take-over interrupts it and the agent is told to finish it. */
  readonly busy: boolean;
  readonly status: string;
  readonly repos: readonly SourceRepo[];
  /** How the conversation travels and which files carry it. */
  readonly conversation: { readonly kind: ConversationKind; readonly files: readonly ConversationFileInfo[]; readonly note: string | null };
  /** Messages typed while the session was paused (D44's queue), delivered on the target with the first message. */
  readonly queued: readonly string[];
  /** Why it cannot be taken over now; empty = it can. */
  readonly blockers: readonly string[];
}

/** A saved folder of the target (and the repos in it) a source repo can be matched against. */
export interface TargetCandidate {
  /** The repo's main checkout. */
  readonly path: string;
  readonly folderId: string | null;
  readonly folderKind: 'workspace' | 'repo';
  /** The saved folder holding it (itself for a repo folder). */
  readonly folderPath: string;
  readonly name: string;
  readonly remoteKey: string | null;
  readonly remoteName: string | null;
}

/** What the target decided for one repo of the session. */
export interface RepoResolution {
  readonly key: string;
  readonly name: string;
  readonly branch: string;
  readonly action: RepoAction;
  /** The target's checkout (main) the repo matched; `null` when it must be cloned. */
  readonly matchedPath: string | null;
  readonly folderId: string | null;
  /** The worktree the session gets there (`worktree` sessions); `null` otherwise. */
  readonly worktreePath: string | null;
  /** Where a clone goes (the typed path, else the default); `null` when no clone. */
  readonly cloneTo: string | null;
  /** The clone's URL (credentials removed); `null` when no clone. */
  readonly cloneUrl: string | null;
  /** Why it is blocked (or a note on what happens). */
  readonly reason: string | null;
  /** What the dialog says: "Use /path/repo", "Clone into /path/repo", the block's reason. */
  readonly summary: string;
  readonly uncommitted: number;
  readonly ahead: number | null;
}

/** What the target machine says about a take-over (`POST /api/takeover/target/plan`). */
export interface TargetPlan {
  readonly machine: { readonly id: string; readonly name: string };
  readonly platform: string;
  /** The CLI the session continues on, and whether it can run here. */
  readonly cli: { readonly provider: CliProviderId; readonly label: string; readonly available: boolean; readonly reason: string | null };
  /** The account the session continues on (D63: the target's default / first with allowance). */
  readonly account: { readonly profileId: string | null; readonly name: string };
  readonly repos: readonly RepoResolution[];
  /** The saved folder the session lives in on the target; `null` when it cannot be decided. */
  readonly folder: { readonly id: string | null; readonly path: string; readonly kind: 'workspace' | 'repo' } | null;
  /** Where the session's process runs on the target (a repo, its worktree, the workspace root). */
  readonly cwd: string | null;
  readonly blockers: readonly string[];
  /** Where clones go by default (next to the target's default folder). */
  readonly defaultCloneParent: string | null;
}

/** The preview the dialog shows: both sides' view before anything changes. */
export interface TakeoverPreview {
  readonly source: SourceInspect;
  readonly target: TargetPlan;
  /** The terminal's `claude` on the source will be stopped (hooked sessions): the dialog says so and asks for a confirmation. */
  readonly stopsTerminal: boolean;
  readonly ok: boolean;
  /** Everything that stops it, from both sides. */
  readonly blockers: readonly string[];
}

/** One repo after the source pushed its work in progress. */
export interface CapturedRepo {
  readonly key: string;
  readonly branch: string;
  readonly remoteName: string;
  readonly remoteUrl: string;
  readonly remoteKey: string;
  /** The temporary remote branch carrying the work. */
  readonly tempBranch: string;
  /** The session branch's tip when it was captured (the WIP commit's parent). */
  readonly baseSha: string;
  /** The WIP commit (everything uncommitted, untracked files included); `null` = no changes, no WIP commit. */
  readonly wipSha: string | null;
  /** What the temp branch points at: the WIP commit, else the branch tip. */
  readonly tipSha: string;
  readonly uncommitted: number;
}

/** What the target did for one repo (the undo log of {@link rollbackActions}). */
export interface AppliedRepo {
  readonly key: string;
  readonly path: string;
  readonly worktreePath: string | null;
  readonly branch: string;
  readonly cloned: boolean;
  readonly addedFolderId: string | null;
  readonly createdBranch: boolean;
  /** The branch's tip on the target before (`null` when the branch was new). */
  readonly previousTip: string | null;
  /** What the main checkout had checked out before (a branch name, or a detached sha). */
  readonly previousHead: string | null;
  readonly tempDeleted: boolean;
  readonly tempDeleteError: string | null;
  /** The private ref the temp branch was fetched into, and the remote / temp branch whose remote-tracking ref the fetch may have made (all removed by the undo). */
  readonly privateRef: string | null;
  readonly remoteName: string | null;
  readonly tempBranch: string | null;
}

/** A temporary remote branch that is still on the remote (the one-click delete). */
export interface Leftover {
  readonly id: string;
  /** A checkout of the repo on the machine that holds this record (where `git push --delete` runs). */
  readonly repoPath: string;
  readonly remoteName: string;
  readonly remoteUrl: string;
  readonly branch: string;
  readonly at: string;
  readonly reason: string | null;
}

/** One step of a running take-over, as the dialog polls it. */
export interface TakeoverStepState {
  readonly id: TakeoverStepId;
  readonly label: string;
  readonly status: TakeoverStepStatus;
  readonly detail: string | null;
}

/** A take-over as the initiating machine reports it (`GET /api/takeover/runs/{id}`). */
export interface TakeoverRun {
  readonly id: string;
  readonly state: 'running' | 'done' | 'failed';
  readonly steps: readonly TakeoverStepState[];
  /** The failure and where it happened; the rollback result is in `rolledBack`. */
  readonly error: { readonly step: TakeoverStepId; readonly message: string } | null;
  /** `true` once a failed take-over was undone (the source is as it was), `false` when the undo itself failed, `null` while not applicable. */
  readonly rolledBack: boolean | null;
  readonly rollbackNotes: readonly string[];
  /** The new session once step 6 succeeded (`sessionId` is how this machine addresses it: local or a remote id). */
  readonly result: { readonly sessionId: string; readonly machineName: string; readonly machineId: string; readonly local: boolean } | null;
  /** Temporary remote branches that could not be deleted (each with the machine to ask and a leftover id). */
  readonly leftovers: ReadonlyArray<Leftover & { readonly machineId: string | null }>;
  /** Every git command both machines ran (never a credential). */
  readonly log: readonly string[];
}

// ── paths (no `node:path`: this module is shared with the UI) ────────────

/** The last segment of a path (either separator). */
function baseName(value: string): string {
  const parts = value.split(/[\\/]+/).filter((part) => part !== '');
  return parts[parts.length - 1] ?? '';
}

/** `parent` + `name` with the separator `parent` uses. */
function joinPath(parent: string, name: string): string {
  const separator = parent.includes('\\') && !parent.includes('/') ? '\\' : '/';
  return `${parent.replace(/[\\/]+$/, '')}${separator}${name}`;
}

// ── names ────────────────────────────────────────────────────────────────

/** The first 8 characters of a session id: the temp branches' namespace. */
export function sessionShortId(sessionId: string): string {
  return sessionId.replace(/[^a-zA-Z0-9]/g, '').slice(0, 8).toLowerCase() || 'session';
}

/** `switchboard/takeover/<session short id>/<branch>`. */
export function tempBranchName(sessionId: string, branch: string): string {
  return `${TAKEOVER_BRANCH_PREFIX}${sessionShortId(sessionId)}/${branch}`;
}

/** `true` for a branch name in the take-over namespace (the only ones the cleanup routes delete). */
export function isTempBranch(branch: string): boolean {
  return branch.startsWith(TAKEOVER_BRANCH_PREFIX) && !branch.includes('..') && !branch.includes(' ') && !branch.endsWith('/');
}

// ── remote URLs ──────────────────────────────────────────────────────────

/**
 * A remote URL without credentials: `https://user:token@host/x.git` →
 * `https://host/x.git` (an ssh URL's user, `git@`, is not a secret and stays).
 */
export function redactUrl(url: string): string {
  const text = url.trim();
  const match = /^([a-z][a-z0-9+.-]*):\/\/([^/@]*)@(.*)$/i.exec(text);
  if (!match) return text;
  const scheme = (match[1] as string).toLowerCase();
  if (scheme === 'ssh' || scheme === 'git+ssh') return text;
  return `${match[1]}://${match[3]}`;
}

/**
 * What two clones of one repo have in common: the remote URL without scheme,
 * credentials, default port, `.git` and a trailing slash, the host lower-cased
 * (`git@github.com:acme/app.git`, `https://user@GitHub.com/acme/app` and
 * `ssh://git@github.com:22/acme/app.git/` all give `github.com/acme/app`). A local
 * path or `file://` URL (a bare repo on disk) gives its path with forward slashes.
 */
export function normalizeRemoteUrl(url: string): string {
  let text = url.trim();
  if (text === '') return '';
  const strip = (value: string): string => value.replace(/\/+$/, '').replace(/\.git$/i, '').replace(/\/+$/, '');
  // A Windows drive path (`C:\repos\app.git`).
  if (/^[A-Za-z]:[\\/]/.test(text)) return strip(`${text.slice(0, 1).toLowerCase()}${text.slice(1).replace(/\\/g, '/')}`);
  const scheme = /^([a-z][a-z0-9+.-]*):\/\/(.*)$/i.exec(text);
  if (scheme) {
    const kind = (scheme[1] as string).toLowerCase();
    let rest = scheme[2] as string;
    if (kind === 'file') {
      rest = rest.replace(/^localhost(?=\/)/i, '');
      if (/^\/[A-Za-z]:\//.test(rest)) rest = rest.slice(1);
      return strip(rest.replace(/\\/g, '/'));
    }
    const at = rest.indexOf('@');
    const slash = rest.indexOf('/');
    if (at >= 0 && (slash < 0 || at < slash)) rest = rest.slice(at + 1);
    const cut = rest.indexOf('/');
    let host = cut < 0 ? rest : rest.slice(0, cut);
    const tail = cut < 0 ? '' : rest.slice(cut);
    const defaults: Record<string, string> = { https: '443', http: '80', ssh: '22', 'git+ssh': '22', git: '9418' };
    host = host.toLowerCase();
    const port = /:(\d+)$/.exec(host);
    if (port && defaults[kind] === port[1]) host = host.slice(0, host.length - (port[0] as string).length);
    return strip(`${host}${tail}`);
  }
  // scp-like `user@host:owner/repo.git`.
  const scp = /^(?:[^@/\s]+@)?([^:/\s]+):(?!\/\/)(.*)$/.exec(text);
  if (scp) return strip(`${(scp[1] as string).toLowerCase()}/${(scp[2] as string).replace(/^\/+/, '')}`);
  // A POSIX path.
  text = text.replace(/\\/g, '/');
  return strip(text);
}

// ── planning ─────────────────────────────────────────────────────────────

/** Options of {@link planRepos}. */
export interface PlanOptions {
  /** `clonePaths[key]`: where the developer asked a missing repo to be cloned. */
  readonly clonePaths?: Readonly<Record<string, string>>;
  /** The session's name (a worktree session gets `../<repo>-wt-<name>` for it). */
  readonly sessionName: string;
  /** The parent of default clone folders (next to the target's default folder); `null` = none known. */
  readonly defaultCloneParent: string | null;
  /** Paths that exist already on the target (a worktree or clone path that collides is blocked). */
  readonly exists?: ReadonlySet<string>;
  /** Branches checked out in another worktree of a candidate repo: `<path>\n<branch>`. */
  readonly checkedOut?: ReadonlySet<string>;
  /** Repos whose working tree is not clean on the target (a main-checkout session cannot check a branch out there): their paths. */
  readonly dirtyTargets?: ReadonlySet<string>;
  /** The path of a worktree (`worktreePath` of `src/core/worktrees.ts`; passed so this module stays free of it). */
  readonly worktreePathOf: (repoPath: string, sessionName: string) => string;
}

/** The candidates that match `repo` by remote, best first (the one named like the repo, then by path). */
export function matchingCandidates(repo: Pick<SourceRepo, 'name' | 'remoteKey'>, candidates: readonly TargetCandidate[]): TargetCandidate[] {
  return candidates
    .filter((candidate) => candidate.remoteKey !== null && candidate.remoteKey !== '' && candidate.remoteKey === repo.remoteKey)
    .sort((a, b) => Number(baseName(b.path) === repo.name) - Number(baseName(a.path) === repo.name) || a.path.localeCompare(b.path));
}

/**
 * Decides, for each of the session's repos, what the target does: use the saved
 * repo that has the same remote (an existing worktree of it counts as the repo:
 * the main checkout is what is matched), clone it (a path to ask for), or refuse
 * (a path that exists, a branch checked out elsewhere, a dirty checkout). Pure.
 */
export function planRepos(repos: readonly SourceRepo[], candidates: readonly TargetCandidate[], options: PlanOptions): RepoResolution[] {
  const exists = options.exists ?? new Set<string>();
  const checkedOut = options.checkedOut ?? new Set<string>();
  const dirty = options.dirtyTargets ?? new Set<string>();
  return repos.map((repo): RepoResolution => {
    const base = { key: repo.key, name: repo.name, branch: repo.branch, uncommitted: repo.dirty.total, ahead: repo.ahead };
    const blocked = (reason: string, extra: Partial<RepoResolution> = {}): RepoResolution => ({
      ...base,
      action: 'blocked',
      matchedPath: null,
      folderId: null,
      worktreePath: null,
      cloneTo: null,
      cloneUrl: null,
      reason,
      summary: reason,
      ...extra,
    });
    if (repo.remoteKey === '') return blocked(`${repo.name} has no remote: its work can only travel through a shared remote`);
    const match = matchingCandidates(repo, candidates)[0];
    if (match) {
      const wantsWorktree = repo.kind === 'worktree';
      const worktreePath = wantsWorktree ? options.worktreePathOf(match.path, options.sessionName) : null;
      if (worktreePath !== null && exists.has(worktreePath)) return blocked(`${worktreePath} exists already on the target`, { matchedPath: match.path, folderId: match.folderId });
      if (checkedOut.has(`${match.path}\n${repo.branch}`)) {
        return blocked(`the branch ${repo.branch} is checked out in another worktree of ${match.path}`, { matchedPath: match.path, folderId: match.folderId });
      }
      if (!wantsWorktree && dirty.has(match.path)) {
        return blocked(`${match.path} has uncommitted changes on the target: commit or stash them first`, { matchedPath: match.path, folderId: match.folderId });
      }
      return {
        ...base,
        action: 'use',
        matchedPath: match.path,
        folderId: match.folderId,
        worktreePath,
        cloneTo: null,
        cloneUrl: null,
        reason: null,
        summary: worktreePath ? `Use ${match.path}; new worktree ${worktreePath} on ${repo.branch}` : `Use ${match.path}; check out ${repo.branch}`,
      };
    }
    const typed = options.clonePaths?.[repo.key]?.trim();
    const cloneTo = typed && typed !== '' ? typed : options.defaultCloneParent ? joinPath(options.defaultCloneParent, repo.name) : null;
    if (cloneTo === null) return blocked(`${repo.name} is not on this machine and no folder is known to clone it into: type one`);
    if (exists.has(cloneTo)) return blocked(`${cloneTo} exists already: choose another folder to clone ${repo.name} into`, { cloneTo, cloneUrl: repo.remoteUrl });
    return {
      ...base,
      action: 'clone',
      matchedPath: null,
      folderId: null,
      worktreePath: repo.kind === 'worktree' ? options.worktreePathOf(cloneTo, options.sessionName) : null,
      cloneTo,
      cloneUrl: repo.remoteUrl,
      reason: null,
      summary: `Not on this machine: clone ${repo.remoteUrl} into ${cloneTo}`,
    };
  });
}

/** What the take-over as a whole refuses on the target, given the resolutions. */
export function planBlockers(resolutions: readonly RepoResolution[]): string[] {
  const out: string[] = [];
  for (const resolution of resolutions) if (resolution.action === 'blocked' && resolution.reason) out.push(resolution.reason);
  return out;
}

// ── rollback ─────────────────────────────────────────────────────────────

/** What had happened when a take-over failed. */
export interface RollbackState {
  /** The steps that finished. */
  readonly done: readonly TakeoverStepId[];
  /** Step 2 stopped a live process of a Switchboard-run session. */
  readonly stoppedLive: boolean;
  /** The session is a hooked terminal session. */
  readonly hooked: boolean;
  /** The hooked terminal's `claude` was stopped. */
  readonly terminalStopped: boolean;
}

/** One undo action, run in the order given. */
export type RollbackAction =
  | 'target-undo-apply'
  | 'target-remove-session'
  | 'target-remove-files'
  | 'source-delete-temp-branches'
  | 'source-resume'
  | 'source-note-terminal-stopped';

/**
 * The undo actions for a failure after `state.done`: the target first (its
 * working tree, then the copied conversation), then the source (the temporary
 * branches, then the session's process). A failure at step 6 or earlier undoes
 * everything; the source's own work tree was never touched (the WIP commit is
 * made without moving the branch or the index), so "undo the WIP commit" is
 * deleting the temp branches. A hooked terminal's stopped `claude` cannot be
 * started again from here: the note says how to resume it.
 */
export function rollbackActions(state: RollbackState): RollbackAction[] {
  const has = (step: TakeoverStepId): boolean => state.done.includes(step);
  const actions: RollbackAction[] = [];
  if (has('resume')) actions.push('target-remove-session');
  if (has('apply') || has('resume')) actions.push('target-undo-apply');
  if (has('transfer') || has('apply') || has('resume')) actions.push('target-remove-files');
  if (has('capture') || has('transfer') || has('apply') || has('resume')) actions.push('source-delete-temp-branches');
  if (state.hooked && state.terminalStopped) actions.push('source-note-terminal-stopped');
  else if (!state.hooked && state.stoppedLive) actions.push('source-resume');
  return actions;
}

// ── texts ────────────────────────────────────────────────────────────────

/** One repo's path change for the first message. */
export interface PathChange {
  readonly name: string;
  readonly from: string;
  readonly to: string;
}

/**
 * The short first message the resumed agent gets (service origin): where the
 * session moved from and to, the paths that changed, and that the working tree
 * is as it was.
 */
export function takeoverMessage(input: { readonly fromMachine: string; readonly toMachine: string; readonly changes: readonly PathChange[]; readonly restored: boolean }): string {
  const paths =
    input.changes.length === 0
      ? 'none'
      : input.changes.map((change) => `${change.from} → ${change.to}${input.changes.length > 1 ? ` (${change.name})` : ''}`).join('; ');
  return [
    `This session moved from ${input.fromMachine} to ${input.toMachine}. Paths changed: ${paths}.`,
    input.restored ? 'The working tree was restored as it was.' : 'The working tree was not restored.',
  ].join(' ');
}

/** The chat divider on the new session. */
export function takenOverLabel(fromMachine: string): string {
  return `Taken over from ${fromMachine}`;
}

/** The note on the old session. */
export function movedToLabel(toMachine: string): string {
  return `Moved to ${toMachine}`;
}

/** The remote id a session on another machine has here (`r~<machine>~<id>`), or the raw id when it is on this machine. */
export function moveLinkId(move: { readonly machineId: string; readonly sessionId: string }, selfId: string | null): string {
  return selfId !== null && move.machineId === selfId ? move.sessionId : remoteId(move.machineId, move.sessionId);
}

/** The dialog's one-line state of a take-over's repos for a hooked session's confirmation. */
export const HOOKED_STOP_WARNING =
  "This session runs in a terminal on the other machine. Taking it over stops that terminal's claude process there (after the conversation and the files are captured); the terminal itself stays open.";
